export let ETHBOX = {
    ADDRESSES: {
        GANACHE: '0xB47089eC00DE7d7bb9862E05Dc07B943F2f87d98',
        RINKEBY: '0x7553D4354Dc145288c278b961eBBE7960877F4c2',
        BSC_TESTNET: '0x1ADD617b988DADDBdF1327d05bc4fD129AA8cE31'
    },
    ABI: [{ "stateMutability": "payable", "type": "fallback" }, { "inputs": [{ "internalType": "uint256", "name": "_box_index", "type": "uint256" }, { "internalType": "bytes32", "name": "_pass_hash", "type": "bytes32" }], "name": "clear_box", "outputs": [], "stateMutability": "payable", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "_recipient", "type": "address" }, { "internalType": "contract ERC20Interface", "name": "_send_token", "type": "address" }, { "internalType": "uint256", "name": "_send_value", "type": "uint256" }, { "internalType": "contract ERC20Interface", "name": "_request_token", "type": "address" }, { "internalType": "uint256", "name": "_request_value", "type": "uint256" }, { "internalType": "bytes32", "name": "_pass_hash_hash", "type": "bytes32" }, { "internalType": "uint32", "name": "_timestamp", "type": "uint32" }], "name": "create_box", "outputs": [], "stateMutability": "payable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "_box_index", "type": "uint256" }], "name": "get_box", "outputs": [{ "components": [{ "internalType": "address payable", "name": "sender", "type": "address" }, { "internalType": "address", "name": "recipient", "type": "address" }, { "internalType": "bytes32", "name": "pass_hash_hash", "type": "bytes32" }, { "internalType": "contract ERC20Interface", "name": "send_token", "type": "address" }, { "internalType": "uint256", "name": "send_value", "type": "uint256" }, { "internalType": "contract ERC20Interface", "name": "request_token", "type": "address" }, { "internalType": "uint256", "name": "request_value", "type": "uint256" }, { "internalType": "uint32", "name": "timestamp", "type": "uint32" }, { "internalType": "bool", "name": "taken", "type": "bool" }], "internalType": "struct ethbox.box", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "get_boxes", "outputs": [{ "components": [{ "internalType": "address payable", "name": "sender", "type": "address" }, { "internalType": "address", "name": "recipient", "type": "address" }, { "internalType": "bytes32", "name": "pass_hash_hash", "type": "bytes32" }, { "internalType": "contract ERC20Interface", "name": "send_token", "type": "address" }, { "internalType": "uint256", "name": "send_value", "type": "uint256" }, { "internalType": "contract ERC20Interface", "name": "request_token", "type": "address" }, { "internalType": "uint256", "name": "request_value", "type": "uint256" }, { "internalType": "uint32", "name": "timestamp", "type": "uint32" }, { "internalType": "bool", "name": "taken", "type": "bool" }], "internalType": "struct ethbox.box[]", "name": "", "type": "tuple[]" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "get_num_boxes", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }]
};

export let TOKEN_DISPENSER = {
    ADDRESSES: {
        GANACHE: '0x6630f98918F87E06d1A377A1db0567AE7B4225b0',
        RINKEBY: '0x54678DF558664F0e45543Bee9dcbcE9D9C1fD351',
        BSC_TESTNET: '0x446B34aDE32E3A8FD9f73246740173b6a929aee6'
    },
    ABI: [{ "inputs": [], "stateMutability": "nonpayable", "type": "constructor" }, { "stateMutability": "payable", "type": "fallback" }, { "inputs": [{ "internalType": "contract ERC20Interface", "name": "_token", "type": "address" }, { "internalType": "address", "name": "_who", "type": "address" }], "name": "get_token_balance", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "_value", "type": "uint256" }, { "internalType": "contract ERC20Interface", "name": "_token", "type": "address" }], "name": "give_token", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "token1", "outputs": [{ "internalType": "contract ERC20Interface", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "token2", "outputs": [{ "internalType": "contract ERC20Interface", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "token3", "outputs": [{ "internalType": "contract ERC20Interface", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" }]
};

export let ERC20_ABI = [{ "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "tokenOwner", "type": "address" }, { "indexed": true, "internalType": "address", "name": "spender", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "tokens", "type": "uint256" }], "name": "Approval", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "from", "type": "address" }, { "indexed": true, "internalType": "address", "name": "to", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "tokens", "type": "uint256" }], "name": "Transfer", "type": "event" }, { "inputs": [{ "internalType": "address", "name": "tokenOwner", "type": "address" }, { "internalType": "address", "name": "spender", "type": "address" }], "name": "allowance", "outputs": [{ "internalType": "uint256", "name": "remaining", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "spender", "type": "address" }, { "internalType": "uint256", "name": "tokens", "type": "uint256" }], "name": "approve", "outputs": [{ "internalType": "bool", "name": "success", "type": "bool" }], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "tokenOwner", "type": "address" }], "name": "balanceOf", "outputs": [{ "internalType": "uint256", "name": "balance", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "decimals", "outputs": [{ "name": "", "type": "uint8" }], "type": "function" }, { "inputs": [], "name": "totalSupply", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "to", "type": "address" }, { "internalType": "uint256", "name": "tokens", "type": "uint256" }], "name": "transfer", "outputs": [{ "internalType": "bool", "name": "success", "type": "bool" }], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "from", "type": "address" }, { "internalType": "address", "name": "to", "type": "address" }, { "internalType": "uint256", "name": "tokens", "type": "uint256" }], "name": "transferFrom", "outputs": [{ "internalType": "bool", "name": "success", "type": "bool" }], "stateMutability": "nonpayable", "type": "function" }];
